### ISSUE TITLE
option 'application/vnd.ms-word.document.macroenabled.12' in section 'MIME Cache' already exists

### ISSUE THREAD

**Issue by JonnyHaystack** [rchaput/xdg-prefs#5]
Hi there. Firstly, thanks a ton for this program! It's something I'd been looking for for years before I found it, and was even planning on writing my own. Thanks for saving me the trouble :)

This crash seems to occur on startup when there is a duplicate line in `/usr/share/applications/mimeinfo.cache`.
In my case, there were both of these lines:
```
application/vnd.ms-word.document.macroEnabled.12
application/vnd.ms-word.document.macroenabled.12
```
I don't know why this duplicate existed, but it seems that xdg-prefs didn't like it so it just crashed. After removing the duplicate, it works fine again.

Full stack trace, for info:
```
While reading from '/usr/share/applications/mimeinfo.cache' [line 60]: option 'application/vnd.ms-word.document.macroenabled.12' in section 'MIME Cache' already exists
Traceback (most recent call last):
  File "/home/haystack/.local/bin/xdg-prefs", line 8, in <module>
    sys.exit(main())
  File "/home/haystack/.local/lib/python3.8/site-packages/xdgprefs/__main__.py", line 14, in main
    window = MainWindow()
  File "/home/haystack/.local/lib/python3.8/site-packages/xdgprefs/gui/main_window.py", line 23, in __init__
    self.assocdb = AssociationsDatabase()
  File "/home/haystack/.local/lib/python3.8/site-packages/xdgprefs/core/associations_database.py", line 142, in __init__
    self._build_db()
  File "/home/haystack/.local/lib/python3.8/site-packages/xdgprefs/core/associations_database.py", line 150, in _build_db
    self._parse_cache_file(file)
  File "/home/haystack/.local/lib/python3.8/site-packages/xdgprefs/core/associations_database.py", line 169, in _parse_cache_file
    for mimetype, apps in config['MIME Cache'].items():
TypeError: 'NoneType' object is not subscriptable
```

**Comment by JonnyHaystack** [comment]
Actually after a little while, this issue has returned.

**Comment by rchaput** [comment]
Hello there!
Sorry for the long delay, it seems that I have missed the notification. Thank you very much for your interest in this project! I'm glad you found it useful.

I just released a new version with a fix for this bug; the crash should not happen anymore.
Please note that, in case of duplicate entries, the parser will now keep only the last line; I still feel that such files should not contain duplicate lines, but well it seems it happens so I prefer to be safe and allow them.

I'm closing this issue, feel free to reopen if it does not work!
